//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SpaceHunt
{
	public virtual object GraphicsDeviceManager graphics
	{
		get;
		set;
	}

	public virtual object SpriteBatch spriteBatch
	{
		get;
		set;
	}

	public virtual object GameScreen gameScreen
	{
		get;
		set;
	}

	public virtual object MenuScreen menuScreen
	{
		get;
		set;
	}

}

